apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-resume.fullname" . }}
  labels:
    {{- include "python-resume.labels" . | nindent 4 }}
    {{- include "python-resume.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "python-resume.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: Local
  {{- end }}
